const products = [
  {
    title: "iPhone 14 Pro",
    shortDescription: "Latest Apple smartphone",
    description: "Powerful A16 Bionic chip with advanced camera system and dynamic island.",
    price: 999,
    category: "electronics",
    image: "https://i.ibb.co/1Xc7r0k/iphone.jpg",
    userId: "user001",
  },
  {
    title: "Nike Air Max",
    shortDescription: "Comfortable running shoes",
    description: "Breathable, lightweight shoes perfect for running and daily wear.",
    price: 120,
    category: "fashion",
    image: "https://i.ibb.co/6P5k7bK/shoes.jpg",
    userId: "user002",
  },
  {
    title: "MacBook Pro M2",
    shortDescription: "High performance laptop",
    description: "Apple M2 chip, ultra-fast performance for developers and creators.",
    price: 1999,
    category: "electronics",
    image: "https://i.ibb.co/7QKQh8R/macbook.jpg",
    userId: "user003",
  },
  {
    title: "Gaming Headset",
    shortDescription: "Surround sound headset",
    description: "High-quality audio with noise cancellation for gaming experience.",
    price: 89,
    category: "electronics",
    image: "https://i.ibb.co/9g0Qp3m/headset.jpg",
    userId: "user004",
  },
  {
    title: "Wooden Chair",
    shortDescription: "Modern home furniture",
    description: "Stylish and comfortable wooden chair for your home or office.",
    price: 150,
    category: "home",
    image: "https://i.ibb.co/5hTgYkR/chair.jpg",
    userId: "user005",
  },
  {
    title: "Smart Watch",
    shortDescription: "Fitness tracking watch",
    description: "Track your heart rate, steps, and notifications easily.",
    price: 199,
    category: "electronics",
    image: "https://i.ibb.co/0VqXk1B/watch.jpg",
    userId: "user006",
  },
  {
    title: "Backpack",
    shortDescription: "Travel backpack",
    description: "Water-resistant backpack with multiple compartments.",
    price: 60,
    category: "fashion",
    image: "https://i.ibb.co/8sQpJkT/backpack.jpg",
    userId: "user007",
  },
  {
    title: "Coffee Mug",
    shortDescription: "Ceramic mug",
    description: "Perfect mug for coffee, tea, and daily use.",
    price: 15,
    category: "home",
    image: "https://i.ibb.co/0jQ1k2M/mug.jpg",
    userId: "user008",
  },
  {
    title: "Bluetooth Speaker",
    shortDescription: "Portable speaker",
    description: "Powerful bass with long battery life and portable design.",
    price: 75,
    category: "electronics",
    image: "https://i.ibb.co/3cXk9Pz/speaker.jpg",
    userId: "user009",
  },
  {
    title: "Desk Lamp",
    shortDescription: "LED study lamp",
    description: "Energy-efficient LED lamp with adjustable brightness levels.",
    price: 40,
    category: "home",
    image: "https://i.ibb.co/2yXkQ8D/lamp.jpg",
    userId: "user010",
  },
];